baseURL = 'https://option0417.github.io/'
languageCode = 'en-us'
title = "Just for fun"

theme= "m10c"

# Owner Settings
[params]
  author = "W.D Su"
  description = "Just for fun with coding and other wonderful thing"
  avatar = "imgs/profile.jpg"
  favicon = "favicon.ico"


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/option0417"
