baseURL = 'https://option0417.github.io/'
languageCode = 'en-us'
title = "Just for fun"

theme= "m10c"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/option0417"
